pipeline {
    agent any

    environment {
    //  AWS_Cred = 'AWS_Cred'
        GIT_USERNAME = credentials('evf1981').username
        GIT_SSH_KEY = credentials('github-ssh').getPrivateKey()
     }

    options {
        buildDiscarder(logRotator(numToKeepStr: '7'))
        //skipDefaultCheckout(true)
        disableConcurrentBuilds()
        timeout (time: 10, unit: 'MINUTES')
        timestamps() 
    }
    
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'feature-branch-vincent', description: 'Enter the name of the branch')
    }
      
    stage('Clone Repository') {
            steps {
                script {
                    git credentialsId: 'github-ssh',
                        url: 'git@github.com:DEL-ORG/revive-vincent.git',
                        branch: "${params.BRANCH_NAME}"
                }
            }
        }

//     stages {
//         stage('Clone Repository') {
//             steps {
//             withCredentials([usernamePrivateKey(credentialsId: 'github-ssh',
//              usernameVariable: 'GIT_USERNAME',
//             //   passphraseVariable: '',
//               privateKeyVariable: 'GIT_SSH_KEY')]) {
//                 echo "Cloning repository..."
//                 checkout([$class: 'GitSCM', 
//                           branches: [[name: "${params.BRANCH_NAME}"]],
//                           userRemoteConfigs: [[url: 'git@github.com:DEL-ORG/revive-vincent.git']]]) 
//             }
//         }
//     }
// }
}