pipeline {
    agent any

    environment {
        docker_hub_credential = credentials("dockerhub-jenkins")
        github_credential = credentials("github-ssh")
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '7'))
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        timestamps() 
    }
    
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'feature-branch-vincent', description: 'Enter the name of the branch')
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                script {
                    git credentialsId: 'github-ssh',
                        url: 'https://github.com/DEL-ORG/revive-vincent.git',
                        branch: "${params.BRANCH_NAME}"
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
            withCredentials([usernamePassword(credentialsId: 'dockerhub-jenkins',
            usernameVariable: 'DOCKERHUB_USERNAME',
            passwordVariable: 'DOCKERHUB_PASSWORD')]) {
            sh '''
                docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            '''
                }
            }
        }
    

        stage('create directory') {
            steps {
                script {
                    sh """
                    mkdir banana rice 
                    """
                }
            }
        }

        stage('delete directory and file') {
            steps {
                script {
                    sh """
                    rm -rf banana rice 
                    """
                }
            }
        } 
      
    }

}

    

